spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: tulub2005
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true                       
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    
  cache:
    type: simple
    cache-names: alerts,alertsByStatus,alertsByBus,alertsByUser,userDetails

jwt:
  secret: "bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA="
  access-cookie-name: "access_token"
  refresh-cookie-name: "refresh_token"

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.demo: INFO
    org.springframework.security: INFO
    org.springframework.cache: TRACE
    org.hibernate.stat: DEBUG

upload:
  path: uploads

telegram:
  bot:
    enabled: true
    token: 7814036147:AAHGLNheD8PH1z3E5qHDKeNyiMzT6RuOsAM
    chat-id: 810471308
    bot-username: QweBusBot

